#!/bin/sh 

echo "Enter the youtube link"
read link 

echo "Would you like to download audio or video? Enter 1 for video and 0 for audio"
read va 

if [ $va -eq 0 ]; then   
cd ~/Music
echo "What audio format would you like? (mp3, ogg, flac)"
read aformat 

yt-dlp -f 18 -x --audio-format $aformat $link

else 

	cd ~/Videos
	echo "What video format would you like (mp4 or webm) "
	read vformat 
	if [ $vformat = 'mp4' ]; then 
		yt-dlp -f 18 $link 
	else 
		yt-dlp $link
	fi

fi 
